### ISSUE TITLE
 Update HorizontalPodAutoscaler API version and configuration

### ISSUE THREAD

**Issue by ianovski** [bharathkkb/gh-runners#1]
### Description
The configuration for the HorizontalPodAutoscaler no longer works and should to be updated to the `autoscaling/v2` API version.

### Changes Proposed
- Update `apiVersion` from `autoscaling/v2beta1` to `autoscaling/v2`.
- Adjust the configuration to match the new API version.

### Previous Configuration
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: runner-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: runner-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75
```

### Suggested Configuration
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: runner-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: runner-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
            type: Utilization
            averageUtilization: 75
```
